<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Fotografía'),
	'category' => t('avn'),
	'icon' => 'avn_fotografia.png',
	'theme' => 'panels_avn_fotografia',
	'css' => 'avn_fotografia.css',
	'panels' => array(
		'header' => t('Header'),
		'panel_left' => t('Panel Left'),
		'panel_right' => t('Panel Right'),
		'footer' => t('Footer'),
	),
);
