<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Termino'),
	'category' => t('avn'),
	'icon' => 'avn_termino.png',
	'theme' => 'panels_avn_termino',
	'css' => 'avn_termino.css',
	'panels' => array(
		'arriba' => t('Arriba'),
		'medio_izquierda' => t('Medio izquierda'),
		'medio_derecha' => t('Medio derecha'),
		'abajo' => t('Abajo'),
	),
);
