<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Galeria'),
	'category' => t('avn'),
	'icon' => 'avn_galeria.png',
	'theme' => 'panels_avn_galeria',
	'css' => 'avn_galeria.css',
	'panels' => array(
		'header' => t('Header'),
		'middle' => t('Middle'),
		'middle_list' => t('Middle List'),
		'footer' => t('Footer'),
	),
);
