<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Radio 2'),
	'category' => t('avn'),
	'icon' => 'avn_radio2.png',
	'theme' => 'panels_avn_radio2',
	'css' => 'avn_radio2.css',
	'panels' => array(
		'principal' => t('Principal'),
		'cuatro-reproductores' => t('Cuatro reproductores'),
		'emisiones-y-reporte-regional' => t('Emisiones y reporte regional'),
		'micros' => t('Micros'),
		'avances' => t('Avances'),
		'antipodas' => t('Antípodas'),
		'agenda-cultural' => t('Agenda cultural'),
		'hoy' => t('Hoy'),
		'sintesis-informativa' => t('Síntesis Informativa'),
		'entrevistas' => t('Entrevistas'),
		'especiales' => t('Especiales'),
	),
);
