<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Nodo'),
	'category' => t('avn'),
	'icon' => 'avn_nodo.png',
	'theme' => 'panels_avn_nodo',
	'css' => 'avn_nodo.css',
	'panels' => array(
		'arriba' => t('Arriba'),
		'medio_izquierda' => t('Medio izquierda'),
		'medio_derecha' => t('Medio derecha'),
		'abajo' => t('Abajo'),
	),
);
