<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Termino slideshow'),
	'category' => t('avn'),
	'icon' => 'avn_termino_slideshow.png',
	'theme' => 'panels_avn_termino_slideshow',
	'css' => 'avn_termino_slideshow.css',
	'panels' => array(
		'arriba' => t('Arriba'),
		'medio' => t('Medio'),
		'abajo_izquierda' => t('Abajo izquierda'),
		'abajo_derecha' => t('Abajo derecha'),
		'abajo' => t('Abajo'),
	),
);
