<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('Vídeo 2'),
	'category' => t('avn'),
	'icon' => 'avn_video2.png',
	'theme' => 'panels_avn_video2',
	'css' => 'avn_video2.css',
	'panels' => array(
		'horizontal1' => t('En Marcha'),
		'horizontal2_izquierda' => t('Cortes Informativos'),
		'horizontal2_derecha' => t('Archivo Visual'),
		'horizontal3' => t('Encuentros Con'),
	),
);
