<?php
// $Id: twocol.inc,v 1.1.2.3 2010/06/22 15:54:25 merlinofchaos Exp $

// Plugin definition
$plugin = array(
	'title' => t('index3'),
	'category' => t('avn'),
	'icon' => 'avn_index3.png',
	'theme' => 'panels_avn_index3',
	'css' => 'avn_index3.css',
	'panels' => array(
		'horizontal1' => t('Slideshow 4 Noticias'),
		'horizontal2' => t('6 Noticias'),
		'horizontal3_izquierda' => t('9 Noticias'),
		'horizontal3_derecha' => t('Notas Gráfico'),
	),
);
